dist: precise
language: node_js
node_js:
  - 7
  - 8
cache:
  directories:
  - node_modules
install:
  - yarn install
script:
  - yarn run lint
  - yarn run test:coverage
after_success:
  - "yarn run coveralls"
  
  
